from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List,Any

class TestCaseCreate(BaseModel):
    case_number: Optional[int]
    input_data: str
    expected_output: str
    reasoning: Optional[str]
    difficulty_level: Optional[str]

class TestCaseResponse(TestCaseCreate):
    id: str
    case_number: Optional[int]

    class Config:
        from_attributes = True

class BulkTestCaseCreate(BaseModel):
    question_id: str
    test_cases: List[TestCaseCreate]


class GeminiTestCaseResponse(BaseModel):
    """
    Represents the structure of Gemini's AI-generated test case output.
    This model validates that Gemini returns a list of valid TestCaseCreate objects.
    """
    test_cases: List[TestCaseCreate] = Field(
        ...,
        description="List of structured test cases generated by Gemini AI"
    )

class TestCaseResponseItem(BaseModel):
    id: str
    question_id: str
    input_json: Any         # allow dict, list, primitives
    expected_output_json: Any
    reasoning: Optional[str] = None
    difficulty_level: Optional[str] = None
    case_number: Optional[int] = None

    model_config = ConfigDict(from_attributes=True)

class TestCaseResponse(BaseModel):
    message:str
    payload:List[TestCaseResponseItem]
    status:int

class RunCodeRequest(BaseModel):
    question_id: str
    code: str